### ISSUE TITLE
No such process error on brainlife.

### ISSUE THREAD

**Issue by jlhanson5** [frankyeh/dsi-studio-atk#3]
Hello all--

I keep getting a "/var/spool/slurmd/job1473893/slurm_script: line 12: kill: (12497) - No such process" error when trying to run this atk app on brainlife. The .err file has some additional information (so I pasted it below). 
```

Traceback (most recent call last):
  File "./smon", line 78, in <module>
    out=subprocess.check_output(["nvidia-smi", "--query-gpu=index,name,pci.bus_id,driver_version,memory.total,compute_mode", "--format=csv"]).decode("utf-8")
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['nvidia-smi', '--query-gpu=index,name,pci.bus_id,driver_version,memory.total,compute_mode', '--format=csv']' returned non-zero exit status 9.
INFO:    Using cached SIF image
./main: line 31: 12505 Segmentation fault      singularity exec -e docker://dsistudio/dsistudio dsi_studio --action=atk --source=${source} --report=report.txt --flip_by=1 ${bval} ${bvec} ${target} ${other}

real	0m28.479s
user	0m33.275s
sys	0m12.703s
/var/spool/slurmd/job1473893/slurm_script: line 12: kill: (12497) - No such process

```
I wasn't sure what might be happening, etc. (but it looks like others might be having some similar issues). Any ways I could troubleshoot it?

The .log file said this-- 

```
other parameter not used
call dsi_studio --action=atk --source=dwi.nii.gz --report=report.txt --bval=../60b19d29979fdc6ae4835b6a/60b12b8922b42af3d7771134/dwi.bvals --bvec=../60b19d29979fdc6ae4835b6a/60b12b8922b42af3d7771134/dwi.bvecs   
DSI Studio Jun  4 2021, Fang-Cheng Yeh
source=dwi.nii.gz
action=atk
track_id=Fasciculus,Cingulum,Aslant,Cortico,Thalamic_R,Reticular,Optic,Fornix,Corpus
target tracks: Arcuate_Fasciculus_L Arcuate_Fasciculus_R Cingulum_Frontal_Parahippocampal_L Cingulum_Frontal_Parahippocampal_R Cingulum_Frontal_Parietal_L Cingulum_Frontal_Parietal_R Cingulum_Parahippocampal_Parietal_L Cingulum_Parahippocampal_Parietal_R Cingulum_Parahippocampal_L Cingulum_Parahippocampal_R Cingulum_Rarolfactory_L Cingulum_Rarolfactory_R Frontal_Aslant_Tract_L Frontal_Aslant_Tract_R Inferior_Fronto_Occipital_Fasciculus_L Inferior_Fronto_Occipital_Fasciculus_R Inferior_Longitudinal_Fasciculus_L Inferior_Longitudinal_Fasciculus_R Middle_Longitudinal_Fasciculus_L Middle_Longitudinal_Fasciculus_R Parietal_Aslant_Tract_L Parietal_Aslant_Tract_R Superior_Longitudinal_Fasciculus1_L Superior_Longitudinal_Fasciculus1_R Superior_Longitudinal_Fasciculus2_L Superior_Longitudinal_Fasciculus2_R Superior_Longitudinal_Fasciculus3_L Superior_Longitudinal_Fasciculus3_R Uncinate_Fasciculus_L Uncinate_Fasciculus_R Vertical_Occipital_Fasciculus_L Vertical_Occipital_Fasciculus_R Corticobulbar_Tract_L Corticobulbar_Tract_R Corticopontine_Tract_Frontal_L Corticopontine_Tract_Frontal_R Corticopontine_Tract_Parietal_L Corticopontine_Tract_Parietal_R Corticopontine_Tract_Occipital_L Corticopontine_Tract_Occipital_R Corticospinal_Tract_L Corticospinal_Tract_R Corticostriatal_Tract_Anterior_L Corticostriatal_Tract_Anterior_R Corticostriatal_Tract_Posterior_L Corticostriatal_Tract_Posterior_R Corticostriatal_Tract_Superior_L Corticostriatal_Tract_Superior_R Thalamic_Radiation_Anterior_L Thalamic_Radiation_Anterior_R Thalamic_Radiation_Posterior_L Thalamic_Radiation_Posterior_R Thalamic_Radiation_Superior_L Thalamic_Radiation_Superior_R Fornix_L Fornix_R Optic_Radiation_L Optic_Radiation_R Reticular_Tract_L Reticular_Tract_R Corpus_Callosum_Forceps_Minor Corpus_Callosum_Body Corpus_Callosum_Tapetum Corpus_Callosum_Forceps_Major
export_template_trk=0
default_mask=0
overwrite=0
export_trk=1
export_stat=1
tip=32
interpolation=2
track_voxel_ratio=2
tolerance=16,18,20
length_ratio=1.25
processing dwi
bval=../60b19d29979fdc6ae4835b6a/60b12b8922b42af3d7771134/dwi.bvals
bvec=../60b19d29979fdc6ae4835b6a/60b12b8922b42af3d7771134/dwi.bvecs
flip_by=1
check_btable=1
aligning with MNI ac-pc
translocation=-0.976983 2.59132 0.949799
rotation=0.172037 0.0148884 0.0236016
scaling=1 1 1
shear=0 0 0
R2 for ac-pc alignment=0.537754
rotating
reconstruct DWI
checking b-table
012=BEST,012fx=-10%,012fy=-9%,012fz=-10%,021=-15%,021fx=-15%,021fy=-20%,021fz=-20%
102=-12%,102fx=-16%,102fy=-17%,102fz=-12%,120=-17%,120fx=-17%,120fy=-18%,120fz=-18%
210=-9%,210fx=-14%,210fy=-9%,210fz=-14%,201=-19%,201fx=-18%,201fy=-18%,201fz=-19%
GQI reconstruction
```

Many thanks,
Jamie.

**Comment by frankyeh** [comment]
I will check the singularity and see if I can fix the problem.
Frank
